name       : libaccounts-qt
version    : '1.16'
release    : 3
source     :
    - https://gitlab.com/accounts-sso/libaccounts-qt/-/archive/VERSION_1.16/libaccounts-qt-VERSION_1.16.tar.gz : 3e527b151ee87e851b0f027214bda1353d8e48e10a5b54109f1e4b7d422a7de3
license    : LGPL-2.1-only
component  : programming
summary    : QT library for single sign on
description: |
    Qt-based client library for the accounts database
builddeps  :
    - pkgconfig(libaccounts-glib)
    - pkgconfig(liblab_gamut)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5WebKit)
    - doxygen
rundeps    :
    - devel :
        - libaccounts-glib-devel
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"

    # remove HTML docs
    rm -rf $installdir/usr/share/doc
