name       : libaccounts-qt
version    : 1.15
release    : 1
source     :
    - git|https://gitlab.com/accounts-sso/libaccounts-qt.git : 5b272ae218ccdf1f67f4eed92e2cdbe21c56ceb8
license    : LGPL-2.1-only
component  : programming
summary    : QT library for single sign on
description: |
    Qt-based client library for the accounts database
builddeps  :
    - pkgconfig(libaccounts-glib)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5WebKit)
    - doxygen
    - graphviz-devel
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
